version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    environment:
      ADMINER_DESIGN: nette
    ports:
      - 8080:8080
volumes:
  pgdata:
